name = "fpm"
version = "0.7.0"
license = "MIT"
author = "fpm maintainers"
maintainer = ""
copyright = "2020 fpm contributors"

[dependencies]
[dependencies.toml-f]
git = "https://github.com/toml-f/toml-f"
rev = "963082b9a1ef1833c2cd2d29dc037dbdb42d4b84"

[dependencies.M_CLI2]
git = "https://github.com/urbanjost/M_CLI2.git"
rev = "7264878cdb1baff7323cc48596d829ccfe7751b8"

[dependencies.jonquil]
git = "https://github.com/toml-f/jonquil"
rev = "05d30818bb12fb877226ce284b9a3a41b971a889"

[[test]]
name = "cli-test"
source-dir = "test/cli_test"
main = "cli_test.f90"

[[test]]
name = "new-test"
source-dir = "test/new_test"
main = "new_test.f90"

[[test]]
name = "fpm-test"
source-dir = "test/fpm_test"
main = "main.f90"

[[test]]
name = "help-test"
source-dir = "test/help_test"
main = "help_test.f90"
