name = "fpm"
version = "0.8.1"
license = "MIT"
author = "fpm maintainers"
maintainer = ""
copyright = "2020 fpm contributors"

[preprocess]
[preprocess.cpp]
macros=["FPM_RELEASE_VERSION={version}"]

[dependencies]
toml-f.git = "https://github.com/toml-f/toml-f"
toml-f.rev = "54686e45993f3a9a1d05d5c7419f39e7d5a4eb3f"
M_CLI2.git = "https://github.com/urbanjost/M_CLI2.git"
M_CLI2.rev = "7264878cdb1baff7323cc48596d829ccfe7751b8"
fortran-regex.git  = "https://github.com/perazz/fortran-regex"
fortran-regex.tag  = "1.1.2"
jonquil.git = "https://github.com/toml-f/jonquil"
jonquil.rev = "05d30818bb12fb877226ce284b9a3a41b971a889"

[[test]]
name = "cli-test"
source-dir = "test/cli_test"
main = "cli_test.f90"

[[test]]
name = "new-test"
source-dir = "test/new_test"
main = "new_test.f90"

[[test]]
name = "fpm-test"
source-dir = "test/fpm_test"
main = "main.f90"

[[test]]
name = "help-test"
source-dir = "test/help_test"
main = "help_test.f90"

