name = "fpm"
version = "0.8.0"
license = "MIT"
author = "fpm maintainers"
maintainer = ""
copyright = "2020 fpm contributors"

[preprocess]
[preprocess.cpp]
macros=["FPM_RELEASE_VERSION={version}"]

[dependencies]
toml-f.git = "https://github.com/toml-f/toml-f"
toml-f.rev = "54686e45993f3a9a1d05d5c7419f39e7d5a4eb3f"
M_CLI2.git = "https://github.com/urbanjost/M_CLI2.git"
M_CLI2.rev = "7264878cdb1baff7323cc48596d829ccfe7751b8"
jonquil.git = "https://github.com/toml-f/jonquil"
jonquil.rev = "05d30818bb12fb877226ce284b9a3a41b971a889"

[build]
auto-tests = false
