name = "test_mpi_cpp"
version = "0.1.0"
license = "license"
author = "Federico Perini"
maintainer = "federico.perini@hello.world"
copyright = "Copyright 2023, Federico Perini and the fpm maintainers"

[[executable]]
name = "test-mpi-cpp"
main = "main.cpp"

[fortran]
implicit-typing=true
implicit-external=true

[dependencies]
mpi = true

[install]
library = false
