name = "cpp_files"
version = "0.1.0"
license = "license"
author = "arteevraina"
maintainer = "arteevraina@gmail.com"
copyright = "Copyright 2022, arteevraina"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
